# Generated by Django 4.0.10 on 2023-05-10 05:45

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyMainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', markdownx.models.MarkdownxField()),
                ('Description', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
