# Generated by Django 4.0.10 on 2023-05-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscripts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymainmenu',
            old_name='Description',
            new_name='application_list',
        ),
    ]
